project:
  type: website
  output-dir: docs
  
website:
  title: "3D Rendering of Multitemporal Hyperspectral Data"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: github
        href: https://github.com/LochlinE/proximalSensingWebTest
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Lochlin Ermatinger"

format:
  html:
    theme: cerulean
    toc: true

editor: source

